package CORBAServer;


/**
* CORBAServer/StockHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/starcraftman/programming/423DistributedProject/a2/423-a2/src/corba/base/interface.idl
* Sunday, November 4, 2012 6:35:54 o'clock AM EST
*/

abstract public class StockHelper
{
  private static String  _id = "IDL:CORBAServer/Stock:1.0";

  public static void insert (org.omg.CORBA.Any a, CORBAServer.Stock_s[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static CORBAServer.Stock_s[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = CORBAServer.Stock_sHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (CORBAServer.Stock_tHelper.id (), "Stock_t", __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (CORBAServer.StockHelper.id (), "Stock", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static CORBAServer.Stock_s[] read (org.omg.CORBA.portable.InputStream istream)
  {
    CORBAServer.Stock_s value[] = null;
    int _len0 = istream.read_long ();
    value = new CORBAServer.Stock_s[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = CORBAServer.Stock_tHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, CORBAServer.Stock_s[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      CORBAServer.Stock_tHelper.write (ostream, value[_i0]);
  }

}
