package CORBAServer;


/**
* CORBAServer/StockHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/starcraftman/programming/423DistributedProject/a2/423-a2/src/corba/base/interface.idl
* Sunday, November 4, 2012 6:35:54 o'clock AM EST
*/

public final class StockHolder implements org.omg.CORBA.portable.Streamable
{
  public CORBAServer.Stock_s value[] = null;

  public StockHolder ()
  {
  }

  public StockHolder (CORBAServer.Stock_s[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CORBAServer.StockHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CORBAServer.StockHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CORBAServer.StockHelper.type ();
  }

}
