package CORBAServer;


/**
* CORBAServer/CorbaInterruptedException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/starcraftman/programming/423DistributedProject/a2/423-a2/src/corba/base/interface.idl
* Sunday, November 4, 2012 6:35:54 o'clock AM EST
*/

public final class CorbaInterruptedException extends org.omg.CORBA.UserException
{
  public String message = null;

  public CorbaInterruptedException ()
  {
    super(CorbaInterruptedExceptionHelper.id());
  } // ctor

  public CorbaInterruptedException (String _message)
  {
    super(CorbaInterruptedExceptionHelper.id());
    message = _message;
  } // ctor


  public CorbaInterruptedException (String $reason, String _message)
  {
    super(CorbaInterruptedExceptionHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class CorbaInterruptedException
