package CORBAServer;


/**
* CORBAServer/CorbaIOException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/starcraftman/programming/423DistributedProject/a2/423-a2/src/corba/base/interface.idl
* Sunday, November 4, 2012 6:35:54 o'clock AM EST
*/

public final class CorbaIOException extends org.omg.CORBA.UserException
{
  public String message = null;

  public CorbaIOException ()
  {
    super(CorbaIOExceptionHelper.id());
  } // ctor

  public CorbaIOException (String _message)
  {
    super(CorbaIOExceptionHelper.id());
    message = _message;
  } // ctor


  public CorbaIOException (String $reason, String _message)
  {
    super(CorbaIOExceptionHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class CorbaIOException
