package CORBAServer;


/**
* CORBAServer/CorbaInetAddressException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/starcraftman/programming/423DistributedProject/a2/423-a2/src/corba/base/interface.idl
* Sunday, November 4, 2012 6:35:54 o'clock AM EST
*/

public final class CorbaInetAddressException extends org.omg.CORBA.UserException
{
  public String message = null;

  public CorbaInetAddressException ()
  {
    super(CorbaInetAddressExceptionHelper.id());
  } // ctor

  public CorbaInetAddressException (String _message)
  {
    super(CorbaInetAddressExceptionHelper.id());
    message = _message;
  } // ctor


  public CorbaInetAddressException (String $reason, String _message)
  {
    super(CorbaInetAddressExceptionHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class CorbaInetAddressException
