package CORBAServer;


/**
* CORBAServer/CorbaNotEnoughStockException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/starcraftman/programming/423DistributedProject/a2/423-a2/src/corba/base/interface.idl
* Sunday, November 4, 2012 6:35:54 o'clock AM EST
*/

public final class CorbaNotEnoughStockException extends org.omg.CORBA.UserException
{
  public String message = null;

  public CorbaNotEnoughStockException ()
  {
    super(CorbaNotEnoughStockExceptionHelper.id());
  } // ctor

  public CorbaNotEnoughStockException (String _message)
  {
    super(CorbaNotEnoughStockExceptionHelper.id());
    message = _message;
  } // ctor


  public CorbaNotEnoughStockException (String $reason, String _message)
  {
    super(CorbaNotEnoughStockExceptionHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class CorbaNotEnoughStockException
