package CORBAServer;


/**
* CORBAServer/RetailStoreOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/starcraftman/programming/423DistributedProject/a2/423-a2/src/corba/base/interface.idl
* Sunday, November 4, 2012 6:35:54 o'clock AM EST
*/


/* Attempting to stay somewhat close to my original design.	*/
public interface RetailStoreOperations 
{
  CORBAServer.Result_s buyItems (String cID, int itemID, int numItems, String initStore) throws CORBAServer.CorbaNotEnoughStockException, CORBAServer.CorbaIOException, CORBAServer.CorbaInterruptedException;
  CORBAServer.Result_s returnItems (String cID, int itemID, int numItems) throws CORBAServer.CorbaIOException, CORBAServer.CorbaInterruptedException;
  CORBAServer.Result_s exchange (String cID, int bItemID, int bNumItems, int dItemID, int dNumItems) throws CORBAServer.CorbaNotEnoughStockException, CORBAServer.CorbaIOException, CORBAServer.CorbaInterruptedException;
  CORBAServer.Stock_s[] checkStock (int itemID) throws CORBAServer.CorbaIOException, CORBAServer.CorbaInetAddressException;
} // interface RetailStoreOperations
