package CORBAServer;

/**
* CORBAServer/RetailStoreHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/starcraftman/programming/423DistributedProject/a2/423-a2/src/corba/base/interface.idl
* Sunday, November 4, 2012 6:35:54 o'clock AM EST
*/


/* Attempting to stay somewhat close to my original design.	*/
public final class RetailStoreHolder implements org.omg.CORBA.portable.Streamable
{
  public CORBAServer.RetailStore value = null;

  public RetailStoreHolder ()
  {
  }

  public RetailStoreHolder (CORBAServer.RetailStore initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CORBAServer.RetailStoreHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CORBAServer.RetailStoreHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CORBAServer.RetailStoreHelper.type ();
  }

}
