package CORBAServer;


/**
* CORBAServer/RetailStore.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/starcraftman/programming/423DistributedProject/a2/423-a2/src/corba/base/interface.idl
* Sunday, November 4, 2012 6:35:54 o'clock AM EST
*/


/* Attempting to stay somewhat close to my original design.	*/
public interface RetailStore extends RetailStoreOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface RetailStore
