package CORBAServer;


/**
* CORBAServer/RetailStorePOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/starcraftman/programming/423DistributedProject/a2/423-a2/src/corba/base/interface.idl
* Sunday, November 4, 2012 6:35:54 o'clock AM EST
*/


/* Attempting to stay somewhat close to my original design.	*/
public class RetailStorePOATie extends RetailStorePOA
{

  // Constructors

  public RetailStorePOATie ( CORBAServer.RetailStoreOperations delegate ) {
      this._impl = delegate;
  }
  public RetailStorePOATie ( CORBAServer.RetailStoreOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public CORBAServer.RetailStoreOperations _delegate() {
      return this._impl;
  }
  public void _delegate (CORBAServer.RetailStoreOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public CORBAServer.Result_s buyItems (String cID, int itemID, int numItems, String initStore) throws CORBAServer.CorbaNotEnoughStockException, CORBAServer.CorbaIOException, CORBAServer.CorbaInterruptedException
  {
    return _impl.buyItems(cID, itemID, numItems, initStore);
  } // buyItems

  public CORBAServer.Result_s returnItems (String cID, int itemID, int numItems) throws CORBAServer.CorbaIOException, CORBAServer.CorbaInterruptedException
  {
    return _impl.returnItems(cID, itemID, numItems);
  } // returnItems

  public CORBAServer.Result_s exchange (String cID, int bItemID, int bNumItems, int dItemID, int dNumItems) throws CORBAServer.CorbaNotEnoughStockException, CORBAServer.CorbaIOException, CORBAServer.CorbaInterruptedException
  {
    return _impl.exchange(cID, bItemID, bNumItems, dItemID, dNumItems);
  } // exchange

  public CORBAServer.Stock_s[] checkStock (int itemID) throws CORBAServer.CorbaIOException, CORBAServer.CorbaInetAddressException
  {
    return _impl.checkStock(itemID);
  } // checkStock

  private CORBAServer.RetailStoreOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class RetailStorePOATie
