package CORBAServer;


/**
* CORBAServer/Stock_tHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/starcraftman/programming/423DistributedProject/a2/423-a2/src/corba/base/interface.idl
* Sunday, November 4, 2012 6:35:54 o'clock AM EST
*/

abstract public class Stock_tHelper
{
  private static String  _id = "IDL:CORBAServer/Stock_t:1.0";

  public static void insert (org.omg.CORBA.Any a, CORBAServer.Stock_s that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static CORBAServer.Stock_s extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = CORBAServer.Stock_sHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (CORBAServer.Stock_tHelper.id (), "Stock_t", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static CORBAServer.Stock_s read (org.omg.CORBA.portable.InputStream istream)
  {
    CORBAServer.Stock_s value = null;
    value = CORBAServer.Stock_sHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, CORBAServer.Stock_s value)
  {
    CORBAServer.Stock_sHelper.write (ostream, value);
  }

}
